version: "3.4"
services:

  sample-app-api:
    container_name: sample-app-api
    environment:
      ConnectionStrings__SampleAppContext: "Data Source=sql-server-database; Initial Catalog=SampleApp; User Id=sa; Password=1StrongPassword*"
    working_dir: /app
    image: 872175912550.dkr.ecr.us-east-1.amazonaws.com/sample-app-api:latest
    depends_on:
      - sql-server-database
    ports:
      - "80:80"

  sql-server-database:
    container_name: sql-server-database
    # The following image supports AMD64 and also ARM64 chips (M1 and M2)
    image: mcr.microsoft.com/azure-sql-edge
    user: root
    environment:
      MSSQL_SA_PASSWORD: 1StrongPassword*
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  migrations:
    container_name: migrations
    image: 872175912550.dkr.ecr.us-east-1.amazonaws.com/sample-app-api-migrations:latest
    working_dir: /app
    environment:
      PATH: "$PATH:$HOME/:dotnet/tools/"
      PROJECT: SampleApp.Infrastructure/SampleApp.Infrastructure.csproj
      STARTUP_PROJECT: SampleApp.Web/SampleApp.Web.csproj
      SQL_CONTEXT_CLASS: SampleAppContext
      ConnectionStrings__SampleAppContext: "Data Source=sql-server-database; Initial Catalog=SampleApp; User Id=sa; Password=1StrongPassword*"
    command: "bash ./Scripts/apply-existing-migrations.sh"
    depends_on:
      - sql-server-database
