version: "3.4"
services:

  sample-app-api:
    container_name: sample-app-api
    env_file:
      - .env
    working_dir: /app
    image: <your-aws-account-id>.dkr.ecr.us-east-1.amazonaws.com/sample-app-api:latest
    depends_on:
      - sql-server-database
    ports:
      - "80:80"

  sql-server-database:
    container_name: sql-server-database
    # The following image supports AMD64 and also ARM64 chips (M1 and M2)
    image: mcr.microsoft.com/azure-sql-edge
    user: root
    env_file:
      - .env
    ports:
      - "1433:1433"
