name: Workflow Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEPLOY_ENVIRONMENT: 'STAGING'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Echo the value of title and lower case
        run: echo "Value of Title ${DEPLOY_ENVIRONMENT^}, Value of Lower ${DEPLOY_ENVIRONMENT,,}
