name: Workflow Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  TITLECASE_ENVIRONMENT: ''
  LOWERCASE_ENVIRONMENT: ''
  DEPLOY_ENVIRONMENT: 'staging'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
              import os
              os.environ["TITLECASE_ENVIRONMENT"] = os.environ["DEPLOY_ENVIRONMENT"].title()
              os.environ["LOWERCASE_ENVIRONMENT"] = os.environ["DEPLOY_ENVIRONMENT"].lower()
              my_var = os.environ.get('TITLECASE_ENVIRONMENT')
              print(f"Value of TITLECASE_ENVIRONMENT: {my_var}")

      - name: Echo the value of TITLECASE_ENVIRONMENT
        run: echo "Value of Title $TITLECASE_ENVIRONMENT, Value of Lower $LOWERCASE_ENVIRONMENT"
