name: Workflow Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  TITLECASE_ENVIRONMENT: ''
  LOWERCASE_ENVIRONMENT: ''
  DEPLOY_ENVIRONMENT: 'staging'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment to title and lower case
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Echo the value of TITLECASE_ENVIRONMENT
        run: echo "Value of Title $TITLECASE_ENVIRONMENT, Value of Lower $LOWERCASE_ENVIRONMENT"
