name: Workflow Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEPLOY_ENVIRONMENT: 'staging'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: To title and to lower
        run: ${DEPLOY_ENVIRONMENT^}

      - name: Echo the value of title and lower case
        env:
          TITLE_CASE_ENVIRONMENT: "${DEPLOY_ENVIRONMENT^}"
          LOWER_CASE_ENVIRONMENT: "${DEPLOY_ENVIRONMENT,,}"
        run: echo "Value of Title $TITLE_CASE_ENVIRONMENT, Value of Lower $LOWER_CASE_ENVIRONMENT"
