name: Workflow Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  TARGET_ENVIRONMENT: 'staging'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Echo the value of title and lower case
        run: |
          environment_title_case=$(echo "$TARGET_ENVIRONMENT" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')
          environment_lower_case=$(echo "$TARGET_ENVIRONMENT" | tr '[:upper:]' '[:lower:]')
          echo "Value of Title $environment_title_case, Value of Lower $environment_lower_case"
